<link rel="stylesheet" type="text/css" href="{{ url('css/font-awesome/css/font-awesome.css') }}">
<link rel="stylesheet" type="text/css" href="{{ url('css/plugins/datatables/datatables.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ url('css/bootstrap.css') }}">
<link rel="stylesheet" type="text/css" href="{{ url('css/animate.css') }}">
<link rel="stylesheet" type="text/css" href="{{ url('css/plugins/select2/select2.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ url('css/plugins/datepicker/datepicker3.css') }}">
<link rel="stylesheet" type="text/css" href="{{ url('css/style.css') }}">
<link rel="stylesheet" type="text/css" href="{{ url('css/lightbox.css') }}">
<link rel="stylesheet" type="text/css" href="{{ url('css/plugins/dropzone/basic.css') }}">
<link rel="stylesheet" type="text/css" href="{{ url('css/plugins/dropzone/dropzone.css') }}">
<link rel="stylesheet" type="text/css" href="{{ url('css/plugins/summernote/summernote.css') }}">
<link rel="stylesheet" type="text/css" href="{{ url('css/plugins/summernote/summernote-bs3.css') }}">
<link rel="stylesheet" type="text/css" href="{{ url('css/plugins/colorpicker/bootstrap-colorpicker.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ url('css/sweetalert.min.css') }}">